name: "BRAD'S WEB LOG"
description: "You ascend to the status of Demigod..."

url: "https://bsimm.github.io"
baseurl: ""

markdown: kramdown
highlighter: rouge
permalink: :year/:month/:title.html

kramdown:
  input: GFM
  syntax_highlighter: rouge
